export 'obtener_data_user.dart' show obtenerDataUser;
export 'add_user.dart' show addUser;
export 'generar_codigo_user.dart' show generarCodigoUser;
export 'eliminar_usuario.dart' show eliminarUsuario;
export 'update_user.dart' show updateUser;
export 'calcular_nota.dart' show calcularNota;
export 'obtener_data_por_dia_studients.dart' show obtenerDataPorDiaStudients;
export 'total_actividades_course.dart' show totalActividadesCourse;
export 'validar1_respuesta.dart' show validar1Respuesta;
export 'obtener_data_por_semana_y_categoria.dart'
    show obtenerDataPorSemanaYCategoria;
export 'obtener_data_general.dart' show obtenerDataGeneral;
export 'get_paypal_access_token.dart' show getPaypalAccessToken;
export 'create_paypal_order.dart' show createPaypalOrder;
export 'limpiar_users_answers.dart' show limpiarUsersAnswers;
export 'verificar_preguntas_respondidas.dart'
    show verificarPreguntasRespondidas;
export 'contar_respuestas_correctas.dart' show contarRespuestasCorrectas;
export 'actualizar_resultado_examen.dart' show actualizarResultadoExamen;
export 'create_details_result.dart' show createDetailsResult;
export 'approve_order_paypal.dart' show approveOrderPaypal;
export 'obtener_link_paypal_regreso.dart' show obtenerLinkPaypalRegreso;
export 'redirect_to_paypal_u_r_l_page.dart' show redirectToPaypalURLPage;
export 'descargar_archivo.dart' show descargarArchivo;
export 'code_certificate.dart' show codeCertificate;
export 'porcentaje_course_linea.dart' show porcentajeCourseLinea;
export 'porcentaje_course.dart' show porcentajeCourse;
export 'delete_register.dart' show deleteRegister;
export 'obtener_data_admin.dart' show obtenerDataAdmin;
export 'validar_resultado.dart' show validarResultado;
