name: Build & Deploy Flutter Web to RiskPeru Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Fix collection version conflict
        run: |
          sed -i 's/collection: \^1.19.0/collection: 1.18.0/' pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 147.93.144.223 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh root@147.93.144.223 "echo SSH OK"

      - name: Deploy to Server
        run: |
          rsync -avz --delete build/web/ root@147.93.144.223:/var/www/html/risk/
